# ================================
# Site settings
# ================================
title: Escape from University!
email: ltw528@york.ac.uk
description: >
  A 2D game about escaping a maze at the University of York,
  while evading the dean and collecting sweet treats.
  Created with LibGDX and Java.
github_username: rosie-mae

# ================================
# Build settings
# ================================
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

show_downloads: true
github:
  is_project_page: true
  game_repo: https://github.com/TheDebugThugs/Assessment_Part_2
  jar_url: https://github.com/TheDebugThugs/Assessment_Part_2/releases/download/v2.0.0/debugthugs.jar

# ================================
# Static reports (JaCoCo / PIT)
# ================================
defaults:
  - scope:
      path: "assets/reports"
    values:
      layout: null

keep_files:
  - assets/reports

exclude:
  - core
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor